name: datasophia
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.4
  - numpy=1.19.5
  - pandas>=1.2.4
  - matplotlib
  - jupyterlab
  - ipython
  - scipy
  - scikit-learn>=0.24.1
  - nbstripout
  - seaborn>=0.11.1
  - netCDF4
  - keras>=2.3.1
  - tensorflow>=2.6.2
  - selenium=4.1.0